language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g jasmine
  - jasmine init
  - jasmine examples
  - cordova platform add android
script:
  - jasmine