language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_deploy:
  - npm install now --no-save
  - now rm node-cd --token $NOW_TOKEN --yes || true
deploy:
  - provider: script
    # deploys the application to now.sh
    script: now --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true

#language: node_js
#node_js:
#  - "stable"
#cache:
#  directories:
#    - "node_modules"
#script:
#  - npm run lint
#  - npm run test:coveralls*/